# Generated by Django 5.2 on 2025-05-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries_info_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('timezone_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('zone', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='country',
            name='timezones',
        ),
        migrations.AddField(
            model_name='country',
            name='timezones',
            field=models.ManyToManyField(related_name='timezone_countries', to='countries_info_api.timezone'),
        ),
    ]
