# Generated by Django 5.2 on 2025-05-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries_info_api', '0002_timezone_remove_country_timezones_country_timezones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='cca3',
            field=models.CharField(max_length=10),
        ),
    ]
