# Generated by Django 5.2 on 2025-05-07 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries_info_api', '0004_alter_country_region_alter_country_sub_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
