# Generated by Django 5.2 on 2025-05-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries_info_api', '0005_alter_language_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='continent',
            new_name='continents',
        ),
        migrations.RemoveField(
            model_name='border',
            name='country',
        ),
        migrations.AddField(
            model_name='country',
            name='borders',
            field=models.ManyToManyField(related_name='border_countries', to='countries_info_api.border'),
        ),
    ]
